RSSReader2/Models/Article.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RSSReader2.Models
{
    public class Article
    {
        public int Id { set; get; }
        [Display(Name = "Název")]
        public string? Title { set; get; }
        [Display(Name = "Obsah")]
        public string? Description { set; get; }
        [Display(Name = "Odkaz")]
        public string? Link { set; get; }
        [DataType(DataType.Date)]
        [Display(Name = "Datum publikování")]
        public DateTime? PubDate { set; get; }
        public int RSSFeedId { set; get; }
        public virtual RSSFeed? RSSFeed { set; get; }
    }
}

RSSReader2/Models/RSSFeed.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RSSReader2.Models
{
    public class RSSFeed
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Toto pole je povinné")]
        public string? Url { get; set; }
        [Required(ErrorMessage = "Toto pole je povinné")]
        [Display(Name = "Název")]
        public string? Name { get; set; }
        [Display(Name = "Články")]
        public virtual ICollection<Article>? Articles { set; get; } 
    }
}

RSSReader2/Controllers/RSSFeedsController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using System.Xml.Linq;
using System.ServiceModel.Syndication;
using System.Xml;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSSReader2.Data;
using RSSReader2.Models;

namespace RSSReader2.Controllers
{
    public class RSSFeedsController : Controller
    {
        private readonly RSSReader2Context _context;

        public RSSFeedsController(RSSReader2Context context)
        {
            _context = context;
        }

        // GET: RSSFeeds
        public async Task<IActionResult> Index(string searchString)
        {
            var items = from m in _context.RSSFeed
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.Name!.Contains(searchString));
            }

           // return View(await items.ToListAsync());
            return items != null ? 
                        View(await items.ToListAsync()) :
                        Problem("Entity set 'RSSReader2Context.RSSFeed'  is null.");
        }

        // GET: RSSFeeds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.RSSFeed == null)
            {
                return NotFound();
            }

            var rSSFeed = await _context.RSSFeed
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rSSFeed == null)
            {
                return NotFound();
            }

            return View(rSSFeed);
        }

        // GET: RSSFeeds/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RSSFeeds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Url,Name")] RSSFeed rSSFeed)
        {
            WebClient wclient = new WebClient();
            string RSSData = wclient.DownloadString(rSSFeed.Url);
            XDocument xml = XDocument.Parse(RSSData);

            ICollection<Article> Articles = GetArticlesFromXml(xml);

            /*var RSSFeedData = from x in xml.Descendants("item")
                               select new Article
                               {
                                   Title = (string)x.Element("title"),
                                   Link = (string)x.Element("link"),
                                   Description = (string)x.Element("description"),
                                   PubDate = (string)x.Element("pubDate"),
                                   RSSFeed = rSSFeed
                               };*/
            /*ICollection<Article> Articles = new List<Article>();
            foreach (var item in articleList)
            {
                Articles.Add(item);
            }*/
            rSSFeed.Articles = Articles;

            if (ModelState.IsValid)
            {
                _context.RSSFeed.Add(rSSFeed);//přidáno .RSSFeed
                await _context.SaveChangesAsync();
                //System.Diagnostics.Debug.WriteLine(rSSFeed.Articles.Count);
                TempData["success"] = "RSS feed byl úspěšně vytvořen.";
                return RedirectToAction(nameof(Index));
                
            }
            return View(rSSFeed);
        }

        // GET: RSSFeeds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.RSSFeed == null)
            {
                return NotFound();
            }

            var rSSFeed = await _context.RSSFeed.FindAsync(id);
            //var rSSFeedFirst = await _context.RSSFeed.FirstOrDefaultAsync(u => u.Id == id);
            //var rSSFeedSingle = await _context.RSSFeed.SingleOrDefaultAsync(u => u.Id == id);

            if (rSSFeed == null)
            {
                return NotFound();
            }
            return View(rSSFeed);
        }

        // POST: RSSFeeds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Url,Name")] RSSFeed rSSFeed)
        {
            if (id != rSSFeed.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.RSSFeed.Update(rSSFeed);//přidáno .RSSFeed
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RSSFeedExists(rSSFeed.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["success"] = "RSS feed byl úspěšně upraven.";
                return RedirectToAction(nameof(Index));
            }
            return View(rSSFeed);
        }

        // GET: RSSFeeds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.RSSFeed == null)
            {
                return NotFound();
            }

            var rSSFeed = await _context.RSSFeed
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rSSFeed == null)
            {
                return NotFound();
            }

            return View(rSSFeed);
        }

        // POST: RSSFeeds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.RSSFeed == null)
            {
                return Problem("Entity set 'RSSReader2Context.RSSFeed'  is null.");
            }
            var rSSFeed = await _context.RSSFeed.FindAsync(id);
            if (rSSFeed != null)
            {
                _context.RSSFeed.Remove(rSSFeed);
            }
            
            await _context.SaveChangesAsync();
            TempData["success"] = "RSS feed byl úspěšně smazán.";
            return RedirectToAction(nameof(Index));
        }

        // GET: RSSFeeds/Articles/5
        public async Task<IActionResult> Articles(int? id, string dateFrom, string dateTo)
        {
            if (id == null || _context.RSSFeed == null)
            {
                return NotFound();
            }
            
            var rSSFeed = await _context.RSSFeed.Include(a => a.Articles)
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (rSSFeed == null)
            {
                return NotFound();
            }
            
            var articles = rSSFeed.Articles;

            IEnumerable<Article> articlesEnumerable = rSSFeed.Articles;
            if (!String.IsNullOrEmpty(dateFrom) && !String.IsNullOrEmpty(dateTo))
            {
                articles = new List<Article>();
                articlesEnumerable = articlesEnumerable
                    .Where(s => s.PubDate >= DateTime.Parse(dateFrom) && s.PubDate <= DateTime.Parse(dateTo));
                foreach (var article in articlesEnumerable)
                {
                    articles.Add(article);
                }
            }
           
            ViewData["Articles"] = articles;
            return View();
            
        }
        // GET: RSSFeeds/Reload/5
        public async Task<IActionResult> Reload(int? id)
        {
            if (id == null || _context.RSSFeed == null)
            {
                return NotFound();
            }

            var rSSFeed = await _context.RSSFeed
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rSSFeed == null)
            {
                return NotFound();
            }

            return View(rSSFeed);
        }

        // POST: RSSFeeds/Reload/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Reload(int id)
        {
            if (_context.RSSFeed == null)
            {
                return Problem("Entity set 'RSSReader2Context.RSSFeed'  is null.");
            }
            var rSSFeed = await _context.RSSFeed.Include(a => a.Articles).FirstOrDefaultAsync(m => m.Id == id);

            if (rSSFeed != null && rSSFeed.Articles != null)
            {
                //_context.RSSFeed.Remove(rSSFeed);
                
                foreach(var article in rSSFeed.Articles)
                { 
                        _context.Article.Remove(article);
                }
                WebClient wclient = new WebClient();
                string RSSData = wclient.DownloadString(rSSFeed.Url);
                XDocument xml = XDocument.Parse(RSSData);

                ICollection<Article> Articles = GetArticlesFromXml(xml);
                
                rSSFeed.Articles = Articles;
                
            }
            
            await _context.SaveChangesAsync();
            TempData["success"] = "Nové články byly úspěšně načteny.";
            return RedirectToAction(nameof(Articles), new {id = id});
        }


        private bool RSSFeedExists(int id)
        {
          return (_context.RSSFeed?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private ICollection<Article> GetArticlesFromXml(XDocument xml)
        {
            ICollection<Article> Articles = new List<Article>();
            foreach (var x in xml.Descendants("item"))
            {
                Article article = new Article();
                if ((string)x.Element("title") != null)

RSSReader2/Views/RSSFeeds/Articles.cshtml
@model IEnumerable<RSSReader2.Models.Article>

@{
    ViewData["Title"] = "Články";
}

<h1>Články</h1>


@await Html.PartialAsync("PartialDateFilter.cshtml")

<a class="btn btn-danger asp-action="Reload" asp-route-id="@ViewContext.RouteData.Values["id"]" method="post">
    <i class="bi bi-arrow-clockwise"></i> &nbsp; Načíst nové články
</a>

@* <form asp-action="Reload">
    <input type="hidden" asp-for="@ViewContext.RouteData.Values["id"]" />
    <input type="submit" value="Načíst nové články" class="btn btn-danger" />
</form> *@

<div>
    <a class="btn btn-secondary" asp-action="Index" style="margin-top: 5px">
        <i class="bi bi-back"></i> &nbsp; Zpět na seznam feedů
    </a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                 @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                 @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                 @Html.DisplayNameFor(model => model.Link)
            </th>
            <th>
                 @Html.DisplayNameFor(model => model.PubDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@if(ViewData["Articles"] != null){
    foreach (var item in ViewData["Articles"] as IEnumerable<RSSReader2.Models.Article>) {
        <tr>
            <td>
                @item.Title
            </td>
            <td>
                @item.Description
            </td>
            <td> <a href=@item.Link>
                @item.Link</a>
            </td>            
                @if(@item.PubDate != null){
                        <td>@item.PubDate</td>
                    }
                    else
                    {
                        <td>Neuvedeno</td>
                    }                       
        </tr>
               
    }  
}
    </tbody>
</table>

RSSReader2/Views/RSSFeeds/Create.cshtml
@model RSSReader2.Models.RSSFeed

@{
    ViewData["Title"] = "Vytvořit";
}

<h1>Vytvořit</h1>

<h4>RSS feed</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="margin-top: 5px">
                    <i class="bi bi-file-plus"></i> &nbsp; Vytvořit
                </button>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary" asp-action="Index" style="margin-top: 5px">
        <i class="bi bi-back"></i> &nbsp; Zpět na seznam feedů
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSSReader2/Views/RSSFeeds/Delete.cshtml
@model RSSReader2.Models.RSSFeed

@{
    ViewData["Title"] = "Smazat";
}

<h1>Smazat</h1>

<h3>Jste si jistý/á, že to chcete udělat?</h3>
<div>
    <h4>RSS feed</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger">
            <i class="bi bi-file-x"></i> &nbsp; Smazat
        </button> 
        <a class="btn btn-secondary" asp-action="Index">
            <i class="bi bi-back"></i> &nbsp; Zpět na seznam feedů
        </a>
    </form>
</div>

RSSReader2/Views/RSSFeeds/Details.cshtml
@model RSSReader2.Models.RSSFeed

@{
    ViewData["Title"] = "Detaily";
}

<h1>Detaily</h1>

<div>
    <h4>RSS feed</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">
        <i class="bi bi-pencil-square"></i> &nbsp; Upravit
    </a> 
    <a class="btn btn-secondary" asp-action="Index">
        <i class="bi bi-back"></i> &nbsp; Zpět na seznam feedů
    </a>
</div>

RSSReader2/Views/RSSFeeds/Edit.cshtml
@model RSSReader2.Models.RSSFeed

@{
    ViewData["Title"] = "Upravit";
}

<h1>Upravit</h1>

<h4>RSS feed</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="margin-top: 5px">
                    <i class="bi bi-box-arrow-down"></i> &nbsp; Uložit
                </button>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary" asp-action="Index" style="margin-top: 5px">
        <i class="bi bi-back"></i> &nbsp; Zpět na seznam feedů
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSSReader2/Views/RSSFeeds/Index.cshtml
@model IEnumerable<RSSReader2.Models.RSSFeed>

@{
    ViewData["Title"] = "RSS feedy";
}



<h1>RSS feedy</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">
        <i class="bi bi-file-plus"></i> &nbsp; Přidat nový <!--non-braking space - nedělitelná mezera (nerozdělí se na 2 řádky)-->
    </a>
</p>

<form asp-controller="RSSFeeds" asp-action="Index" method="get">
    <p>
        Název: <input type="text" name="searchString" />
        <button type="submit" class="btn btn-primary">
            <i class="bi bi-filter"></i> &nbsp; Filtrovat
        </button>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Articles)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Url)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Articles" asp-route-id="@item.Id">
                        <i class="bi bi-list-columns-reverse"></i> &nbsp; Články
                    </a>
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">
                        <i class="bi bi-pencil-square"></i> &nbsp; Upravit
                </a>
                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">
                        <i class="bi bi-info-square"></i> &nbsp; Detaily
                </a>
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">
                        <i class="bi bi-file-x"></i> &nbsp; Smazat
                </a> 

            </td>
        </tr>
}
    </tbody>
</table>

RSSReader2/Views/RSSFeeds/PartialDateFilter.cshtml
@model DateTime
<form asp-controller="RSSFeeds" asp-action="Articles" method="get">
    <p>
Od: @Html.TextBox("dateFrom", String.Format("{0:d}", Model.ToShortDateString()),
  new { @class = "datefield", type = "date" })  
Do: @Html.TextBox("dateTo", String.Format("{0:d}", Model.ToShortDateString()),
  new { @class = "datefield", type = "date" })
  <button class="btn btn-primary" type="submit" >
            <i class="bi bi-filter"></i> &nbsp; Filtrovat
  </button>
  </p>
</form>